events {}

http {

    upstream rate_limiter {

       server host.docker.internal:8080;
        server host.docker.internal:8081;
        server host.docker.internal:8082;

    }

    server {

        listen 80;

        location / {

            proxy_pass http://rate_limiter;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

    }

}